### PR TITLE
FIX Requests to root dir circumvent index.php

### PR DESCRIPTION
**Pull request by dhensby**
fixes #58

### CODE REVIEW

**Comment by dhensby** [comment]
@tractorcow is this likely to get in to 3.1.10? if not, I'll ask for the docs [here](https://github.com/silverstripe/silverstripe-framework/pull/3905) to be updated to saying 3.1.11

**Comment by tractorcow** [comment]
It's too late to go into 3.1.10 I'm afraid.

**Comment by tractorcow** [comment]
This PR is going into your own installer by the way. Did you mean to make it against the main fork?

**Comment by dhensby** [comment]
Oh gosh. It must have been late when I opened the PR. I'll open one on the ss repo

**Comment by tractorcow** [comment]
Hehe :D

**Pull request closed without merging**
